Update patch set 7
Patch Set 7:

updated the constructors

also fixed "error: cannot find symbol cm.setMobileDataEnabled(true);" in SamsungCDMAv6RIL and SamsungExynos3RIL classes.
Got moved from ConnectivityManager to TelephonyManager.

Patch-set: 7
Reviewer: Gerrit User 1000328 <1000328@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=0