Update patch set 6
Patch Set 6:

> frameworks/opt/net/ims/src/java/com/android/ims/internal/ImsCallSession.java:1075:
 > error: method does not override or implement a method from a
 > supertype
 > @Override

??? That file is not so long (checked now in frameworks/opt/net/ims). Plus you need to tell me the whole error I don't know if that is related to this (it's in another repo too), you need to give me where (and if) your error is related to this commit (at the beginning of the error you should find the file that generated it). Have you tried to compile without this? Is it compiling without this commit? And while using this commit are you sure you have done all the changes needed for your device (in other places)? Which device are you compiling for?

Patch-set: 6